# Generated by Django 2.1.3 on 2019-02-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suitYourself', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='description',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
