# Generated by Django 2.1.3 on 2019-02-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suitYourself', '0002_upload_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='title',
            field=models.CharField(default='No title', max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='description',
            field=models.CharField(default='No description', max_length=300),
        ),
    ]
