# Generated by Django 2.1.3 on 2019-02-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suitYourself', '0003_auto_20190228_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra large')], default='NA', max_length=2),
        ),
    ]
