# Generated by Django 2.1.3 on 2019-02-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suitYourself', '0004_upload_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='price',
            field=models.CharField(default='0.00', max_length=6),
        ),
    ]
