# Generated by Django 2.1.3 on 2019-03-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suitYourself', '0005_upload_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='title',
            field=models.CharField(default='No title', max_length=50),
        ),
    ]
