# Generated by Django 2.1.5 on 2019-03-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suitYourself', '0006_auto_20190307_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='title',
            field=models.CharField(default='No title', max_length=100),
        ),
    ]
